### ISSUE TITLE
Spoke launch checklist

### ISSUE THREAD

**Issue by gfodor** [mozilla/Spoke#294]
- [x] Release process for binaries (Brian)
- [x] Figure out how we're going to notify users of new versions (#312)
- [x] Finalize logo
- [ ] Add icon to launcher if possible
- [x] Landing page design (Greg)
- [ ] Landing page implementation + deployment
- [ ] Landing page video (high speed use-case oriented video, no audio) (Josh)
- [ ] Hello World tutorial video (bring in a sketchfab model, get it ready, create a scene) (Josh)
- [x] Marketing sync wrt content creators using Spoke before launch (Greg)
- [x] Launch blog post draft (Greg)
- [ ] Launch blog post animated GIFs and images (likely drawn from the landing page video)
- [x] Legal pass, need to update `REMIXING.md`, `PROMOTION.md`, ToS, PP, and various metadata bits (Greg)
- [x] Scene uploads should be posted to slack
- [x] Support channels in help menu and on landing page (probably just email address)
- [x] Slack channel callout on landing page
- [x] Sketchfab account set up and collections ready (Jim)
- [x] Add Sketchfab account link from Add Model in Spoke
- [x] Resolve any licensing issues
- [x] Add "made with Spoke" to scene landing page
- [x] Add 'beta' verbiage, add version to landing page
